vich_uploader:
    db_driver: orm


    mappings:
        documents:
            uri_prefix: /documents/inscrits
            upload_destination: '%kernel.project_dir%/public/documents/inscrits'
            namer : Vich\UploaderBundle\Naming\UniqidNamer
            
            delete_on_update: true